### ISSUE TITLE
Wiki doesn't work

### ISSUE THREAD

**Issue by ktakagaki** [slentzen/Grampus#1]
I see a tab now, but clicking on it does nothing.
Can you try creating an empty Wiki page?
Is it also open to editing (for me in particular or in general)?

**Comment by slentzen** [comment]
@ktakagaki 
Try now, I enabled the wiki, but I can't see how I can pull it down as a markdown document

**Comment by slentzen** [comment]
Okay think I got it, cloned the wiki pages into a subfolder of Grampus/wiki
I don't know if it's considered best practice to keep the entire wiki in a separate folder outside of the project, but I figured it is better to have it within the project so it follows the same Git commit history.

**Comment by ktakagaki** [comment]
works thx
